image: Visual Studio 2017

platform: Any CPU

version: 1.4.{build}

branches:
  only:
    - master
    - production

environment:
  nuget:
    secure: lAOgXBlidUDKDMFlDJInIUO7K9vZc4FHLP715QyBp1gP9KFNQjntN70Jo6gi4+bA

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'

before_build:
  - pwsh: mkdir src/CompilerAPI/wwwroot/min

build_script:
  - pwsh: dotnet build -c Release
  - pwsh: dotnet test test/AD.OpenXML.Tests -c Release

  - pwsh: dotnet build -c Release -f netcoreapp2.0 -r rhel-x64 -o /app/rhel-x64
  - docker build .

on_success:
  - pwsh: dotnet nuget push src/AD.OpenXml/bin/release/AD.OpenXml.${env:appveyor_build_version}.nupkg -s https://www.nuget.org/api/v2/package -k ${env:nuget}

#deploy:
#  release: CompilerAPI-v$(appveyor_build_version)
#  description: 'Release description'
#  provider: GitHub
#  auth_token:
#    secure: <your encrypted token> # your encrypted token from GitHub
#  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only