image:
  - Visual Studio 2017

platform:
  - Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

install:
  - pwsh: mkdir src/CompilerAPI/wwwroot/min

build_script:
  - pwsh: dotnet build --configuration Release
  - pwsh: dotnet test test/AD.OpenXML.Tests --configuration Release