image:
  - Visual Studio 2017

platform:
  - Any CPU

install:
  - pwsh: mkdir src/QuestionnairesAPI/wwwroot/min

build_script:
  - pwsh: dotnet build --configuration Release
  - pwsh: dotnet test test/AD.OpenXML.Tests --configuration Release