image:
- Visual Studio 2017
- Ubuntu

version: 2.1.0.{build}

environment:
  global:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'

build_script:
- pwsh: |
    $ErrorActionPreference = "Stop";
    dotnet build src/AD.OpenXml -c Release
    dotnet pack src/AD.OpenXml -c Release

test_script:
- pwsh: |
    $ErrorActionPreference = "Stop";
    dotnet test test/AD.OpenXml.Tests -c Release

artifacts:
- path: 'src\**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: lAOgXBlidUDKDMFlDJInIUO7K9vZc4FHLP715QyBp1gP9KFNQjntN70Jo6gi4+bA
  on:
    CI_WINDOWS: true