//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.OpenXml.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AD.OpenXml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Types xmlns=&quot;http://schemas.openxmlformats.org/package/2006/content-types&quot;&gt;
        ///  &lt;Default Extension=&quot;docx&quot; ContentType=&quot;application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml&quot;/&gt;
        ///  &lt;Default Extension=&quot;rels&quot; ContentType=&quot;application/vnd.openxmlformats-package.relationships+xml&quot;/&gt;
        ///  &lt;Default Extension=&quot;xlsx&quot; ContentType=&quot;application/vnd.openxmlformats-officedocument.spreadsheetml.sheet&quot;/&gt;
        ///  &lt;Default Extension=&quot;xml&quot; ContentType [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _Content_Types_ {
            get {
                return ResourceManager.GetString("_Content_Types_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Properties xmlns=&quot;http://schemas.openxmlformats.org/officeDocument/2006/extended-properties&quot;
        ///            xmlns:vt=&quot;http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes&quot;&gt;
        ///  &lt;Template&gt;Normal.dotm&lt;/Template&gt;
        ///  &lt;TotalTime&gt;0&lt;/TotalTime&gt;
        ///  &lt;Pages&gt;1&lt;/Pages&gt;
        ///  &lt;Words&gt;0&lt;/Words&gt;
        ///  &lt;Characters&gt;0&lt;/Characters&gt;
        ///  &lt;Application&gt;Microsoft Office Word&lt;/Application&gt;
        ///  &lt;DocSecurity&gt;0&lt;/DocSecurity&gt;
        ///  &lt;Lines&gt;0&lt;/Lines&gt;
        ///  &lt;Paragraphs&gt;0&lt;/Paragraphs&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Appendix&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;Appendix&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:numPr&gt;
        ///      &lt;w:numId w:val=&quot;2&quot;/&gt;
        ///    &lt;/w:numPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;0&quot;/&gt;
        ///    &lt;w:pageBreakBefore/&gt;
        ///    &lt;w:spacing w:after=&quot;4800&quot; w:before=&quot;4800&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Appendix {
            get {
                return ResourceManager.GetString("Appendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Bibliography&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Bibliography&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;720&quot; w:hanging=&quot;720&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepLines/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Bibliography {
            get {
                return ResourceManager.GetString("Bibliography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;table&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;BlueTableBasic&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:name w:val=&quot;Blue Table (basic)&quot; /&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:before=&quot;0&quot; w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot; /&gt;
        ///    &lt;w:contextualSpacing /&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;20&quot; /&gt;
        ///  &lt;/w:rPr&gt;
        ///  &lt;w:tblPr&gt;
        ///    &lt;w:tblStyleRowBandSize w:val=&quot;1&quot; /&gt;
        ///    &lt;w:tb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlueTableBasic {
            get {
                return ResourceManager.GetString("BlueTableBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;Box&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Box&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:pBdr&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:sz=&quot;18&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:themeColor=&quot;background1&quot; w:themeShade=&quot;F2&quot;/&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:sz=&quot;18&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:themeColor=&quot;background1&quot; w:themeShade=&quot;F2&quot;/&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;BoxCaption&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Box&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Box Caption&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:contextualSpacing/&gt;
        ///    &lt;w:spacing w:before=&quot;240&quot; w:after=&quot;0&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string BoxCaption {
            get {
                return ResourceManager.GetString("BoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;BoxListBullet&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;ListBullet&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Box List Bullet&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:pBdr&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:sz=&quot;18&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:themeColor=&quot;background1&quot; w:themeShade=&quot;F2&quot;/&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:sz=&quot;18&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:themeColor=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoxListBullet {
            get {
                return ResourceManager.GetString("BoxListBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;BoxSourceNote&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Box Source/Note&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;60&quot;/&gt;
        ///    &lt;w:pBdr&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:sz=&quot;18&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:themeColor=&quot;background1&quot; w:themeShade=&quot;F2&quot;/&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:sz=&quot;18&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:theme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BoxSourceNote {
            get {
                return ResourceManager.GetString("BoxSourceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;CaptionFigure&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Caption Figure&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;60&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///    &lt;w:pBdr&gt;
        ///      &lt;w:top w:val=&quot;single&quot; w:sz=&quot;12&quot; w:space=&quot;4&quot; w:color=&quot;F2F2F2&quot; w:themeColor=&quot;background1&quot; w:themeShade=&quot;F2&quot;/&gt;
        ///      &lt;w:left w:val=&quot;single&quot; w:sz=&quot;12&quot; w:sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CaptionFigure {
            get {
                return ResourceManager.GetString("CaptionFigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;CaptionTable&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Caption Table&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;60&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///    &lt;w:spacing w:before=&quot;240&quot; w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;22&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string CaptionTable {
            get {
                return ResourceManager.GetString("CaptionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;cp:coreProperties xmlns:cp=&quot;http://schemas.openxmlformats.org/package/2006/metadata/core-properties&quot; 
        ///                   xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; 
        ///                   xmlns:dcterms=&quot;http://purl.org/dc/terms/&quot; 
        ///                   xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;dc:creator&gt;508 Programming Application&lt;/dc:creator&gt;
        ///  &lt;cp:lastModifiedBy&gt;508 Programming Application&lt;/cp:lastModifiedBy&gt;
        ///  &lt;cp:revision&gt;0&lt;/cp:r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string core {
            get {
                return ResourceManager.GetString("core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:docDefaults xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:rPrDefault&gt;
        ///    &lt;w:rPr&gt;
        ///      &lt;w:rFonts w:ascii=&quot;Calibri&quot;/&gt;
        ///      &lt;w:sz w:val=&quot;24&quot;/&gt;
        ///    &lt;/w:rPr&gt;
        ///  &lt;/w:rPrDefault&gt;
        ///  &lt;w:pPrDefault&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:spacing w:after=&quot;200&quot; w:before=&quot;0&quot; w:line=&quot;276&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///  &lt;/w:pPrDefault&gt;
        ///&lt;/w:docDefaults&gt;.
        /// </summary>
        internal static string DocDefaults {
            get {
                return ResourceManager.GetString("DocDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;w:document xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:body&gt;
        ///  &lt;/w:body&gt;
        ///&lt;/w:document&gt;.
        /// </summary>
        internal static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///  &lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles&quot; Target=&quot;styles.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings&quot; Target=&quot;settings.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string document_xml_rels {
            get {
                return ResourceManager.GetString("document_xml_rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;character&quot; w:default=&quot;1&quot; w:styleId=&quot;Emphasis&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Emphasis&quot;/&gt;
        ///  &lt;w:qFormat/&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:i/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Emphasis {
            get {
                return ResourceManager.GetString("Emphasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;1stParaExecutiveSummary&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:name w:val=&quot;1st Para Executive Summary&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:color w:val=&quot;005070&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;32&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string ExecutiveSummary1stParagraph {
            get {
                return ResourceManager.GetString("ExecutiveSummary1stParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;ExecutiveSummaryHighlights&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;1stParaExecutiveSummary&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Executive Summary Highlights&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:contextualSpacing/&gt;
        ///    &lt;w:spacing w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;28&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string ExecutiveSummaryHighlights {
            get {
                return ResourceManager.GetString("ExecutiveSummaryHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;ExecutiveSummarySidebarHeaders&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Heading4&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Executive Summary Sidebar Headers&quot;/&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string ExecutiveSummarySidebars {
            get {
                return ResourceManager.GetString("ExecutiveSummarySidebars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;FiguresTablesSourceNote&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Figures/Tables Source/Note&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:contextualSpacing/&gt;
        ///    &lt;w:ind w:left=&quot;58&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;16&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string FigureTableSourceNote {
            get {
                return ResourceManager.GetString("FigureTableSourceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:ftr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:jc w:val=&quot;right&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t&gt;U.S. International Trade Commission |&lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///    &lt;w:fldSimple w:instr=&quot; PAGE   \* MERGEFORMAT &quot;&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:t&gt;&lt;/w:t&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:fldSimple&gt;
        ///  &lt;/w:p&gt;
        ///&lt;/w:ftr&gt;.
        /// </summary>
        internal static string footer1 {
            get {
                return ResourceManager.GetString("footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:ftr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:jc w:val=&quot;left&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:fldSimple w:instr=&quot; PAGE   \* MERGEFORMAT &quot;&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:t&gt;&lt;/w:t&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:fldSimple&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t&gt;| www.usitc.gov&lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///  &lt;/w:p&gt;
        ///&lt;/w:ftr&gt;.
        /// </summary>
        internal static string footer2 {
            get {
                return ResourceManager.GetString("footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;character&quot; w:styleId=&quot;FootnoteReference&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot;/&gt;
        ///  &lt;w:name w:val=&quot;footnote reference&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:vertAlign w:val=&quot;superscript&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string FootnoteReference {
            get {
                return ResourceManager.GetString("FootnoteReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:footnotes xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:footnote w:type=&quot;separator&quot; w:id=&quot;-1&quot;&gt;
        ///    &lt;w:p&gt;
        ///      &lt;w:pPr&gt;
        ///        &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///      &lt;/w:pPr&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:separator/&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:p&gt;
        ///  &lt;/w:footnote&gt;
        ///  &lt;w:footnote w:type=&quot;continuationSeparator&quot; w:id=&quot;0&quot;&gt;
        ///    &lt;w:p&gt;
        ///      &lt;w:pPr&gt;
        ///        &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string footnotes {
            get {
                return ResourceManager.GetString("footnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;FootnoteText&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;footnote text&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:sz w:val=&quot;20&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string FootnoteText {
            get {
                return ResourceManager.GetString("FootnoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:hdr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:pStyle w:val=&quot;Header&quot;/&gt;
        ///      &lt;w:jc w:val=&quot;left&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t&gt;{0}&lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///  &lt;/w:p&gt;
        ///&lt;/w:hdr&gt;.
        /// </summary>
        internal static string header1 {
            get {
                return ResourceManager.GetString("header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:hdr xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:p&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:pStyle w:val=&quot;Header&quot;/&gt;
        ///      &lt;w:jc w:val=&quot;right&quot;/&gt;
        ///    &lt;/w:pPr&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t xml:space=&quot;preserve&quot;&gt;Chapter &lt;/w:t&gt;
        ///    &lt;/w:r&gt;
        ///    &lt;w:fldSimple w:instr=&quot; STYLEREF  &amp;quot;heading 1&amp;quot; \s \* MERGEFORMAT &quot;&gt;
        ///      &lt;w:r&gt;
        ///        &lt;w:t/&gt;
        ///      &lt;/w:r&gt;
        ///    &lt;/w:fldSimple&gt;
        ///    &lt;w:r&gt;
        ///      &lt;w:t xml:space=&quot;preserve&quot;&gt;: &lt;/w:t&gt;
        ///    &lt;/w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header2 {
            get {
                return ResourceManager.GetString("header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading1&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 1&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:numPr&gt;
        ///      &lt;w:numId w:val=&quot;1&quot;/&gt;
        ///    &lt;/w:numPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;0&quot;/&gt;
        ///    &lt;w:pageBreakBefore/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading1 {
            get {
                return ResourceManager.GetString("Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading2&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 2&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;1&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;A58329&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;40&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading2 {
            get {
                return ResourceManager.GetString("Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading3&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 3&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;2&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;005070&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;36&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading3 {
            get {
                return ResourceManager.GetString("Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading4&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 4&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;3&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;A58329&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;28&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading4 {
            get {
                return ResourceManager.GetString("Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading5&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 5&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;4&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;005070&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;24&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading5 {
            get {
                return ResourceManager.GetString("Heading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading6&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 6&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;5&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;A58329&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;24&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading6 {
            get {
                return ResourceManager.GetString("Heading6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading7&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 7&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;6&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;005070&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;24&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading7 {
            get {
                return ResourceManager.GetString("Heading7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading8&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 8&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;7&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;A58329&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;24&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading8 {
            get {
                return ResourceManager.GetString("Heading8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;Heading9&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;heading 9&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;8&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:keepNext/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///    &lt;w:color w:val=&quot;005070&quot;/&gt;
        ///    &lt;w:rFonts w:ascii=&quot;Tahoma&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;24&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heading9 {
            get {
                return ResourceManager.GetString("Heading9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;character&quot; w:styleId=&quot;Hyperlink&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Hyperlink&quot;/&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:color w:val=&quot;0000FF&quot; w:themeColor=&quot;hyperlink&quot;/&gt;
        ///    &lt;w:u w:val=&quot;single&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;ListBullet&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;List Bullet&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:contextualSpacing/&gt;
        ///    &lt;!--&lt;w:numPr&gt;
        ///      &lt;w:numId w:val=&quot;15&quot;/&gt;
        ///    &lt;/w:numPr&gt;--&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string ListBullet {
            get {
                return ResourceManager.GetString("ListBullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:default=&quot;1&quot; w:styleId=&quot;Normal&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:name w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:spacing w:after=&quot;240&quot; w:before=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:numbering xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:abstractNum w:abstractNumId=&quot;0&quot;&gt;
        ///    &lt;w:multiLevelType w:val=&quot;singleLevel&quot;/&gt;
        ///    &lt;w:lvl w:ilvl=&quot;0&quot;&gt;
        ///      &lt;w:start w:val=&quot;1&quot;/&gt;
        ///      &lt;w:numFmt w:val=&quot;decimal&quot;/&gt;
        ///      &lt;w:lvlText w:val=&quot;Chapter %1 &quot;/&gt;
        ///      &lt;w:lvlJc w:val=&quot;left&quot;/&gt;
        ///    &lt;/w:lvl&gt;
        ///  &lt;/w:abstractNum&gt;
        ///  &lt;w:abstractNum w:abstractNumId=&quot;1&quot;&gt;
        ///    &lt;w:multiLevelType w:val=&quot;singleLevel&quot;/&gt;
        ///    &lt;w:lv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Numbering {
            get {
                return ResourceManager.GetString("Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;PreHeading&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Heading1&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Pre Heading&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:numPr&gt;
        ///      &lt;w:numId w:val=&quot;0&quot;/&gt;
        ///    &lt;/w:numPr&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string PreHeading {
            get {
                return ResourceManager.GetString("PreHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Relationships xmlns=&quot;http://schemas.openxmlformats.org/package/2006/relationships&quot;&gt;
        ///  &lt;Relationship Id=&quot;rId1&quot; Type=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument&quot; Target=&quot;word/document.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId2&quot; Type=&quot;http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties&quot; Target=&quot;docProps/core.xml&quot;/&gt;
        ///  &lt;Relationship Id=&quot;rId3&quot; Type=&quot;http://schemas.openxmlformats.org/officeDo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rels {
            get {
                return ResourceManager.GetString("rels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:settings xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///            xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot; 
        ///            xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; 
        ///            xmlns:m=&quot;http://schemas.openxmlformats.org/officeDocument/2006/math&quot; 
        ///            xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; 
        ///            xmlns:w10=&quot;urn:schemas-microsoft-com:office:word&quot; 
        ///            x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;character&quot; w:default=&quot;1&quot; w:styleId=&quot;Strong&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;Strong&quot;/&gt;
        ///  &lt;w:qFormat/&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Strong {
            get {
                return ResourceManager.GetString("Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;StyleNotImplemented&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:name w:val=&quot;Style Not Implemented&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:keepNext/&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:color w:val=&quot;A52A2A&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;22&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string StyleNotImplemented {
            get {
                return ResourceManager.GetString("StyleNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:styles xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///          xmlns:r=&quot;http://schemas.openxmlformats.org/officeDocument/2006/relationships&quot; 
        ///          xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; 
        ///          xmlns:w14=&quot;http://schemas.microsoft.com/office/word/2010/wordml&quot; 
        ///          mc:Ignorable=&quot;w14&quot;&gt;
        ///  &lt;w:docDefaults&gt;
        ///    &lt;w:rPrDefault&gt;
        ///      &lt;w:rPr&gt;
        ///        &lt;w:rFonts w:asciiTheme=&quot;minor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string styles {
            get {
                return ResourceManager.GetString("styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:styles xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;ListNumber&quot;&gt;
        ///    &lt;w:name w:val=&quot;List Number&quot;/&gt;
        ///    &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///    &lt;w:uiPriority w:val=&quot;99&quot;/&gt;
        ///    &lt;w:unhideWhenUsed/&gt;
        ///    &lt;w:rsid w:val=&quot;00FA68DE&quot;/&gt;
        ///    &lt;w:pPr&gt;
        ///      &lt;w:numPr&gt;
        ///        &lt;w:numId w:val=&quot;20&quot;/&gt;
        ///      &lt;/w:numPr&gt;
        ///      &lt;w:spacing w:after=&quot;240&quot;/&gt;
        ///      &lt;w:contextualSpacing/&gt;
        ///    &lt;/w:pPr&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Styles1 {
            get {
                return ResourceManager.GetString("Styles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;character&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;Subscript&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;subscript&quot;/&gt;
        ///  &lt;w:qFormat/&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:vertAlign w:val=&quot;subscript&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;character&quot; w:customStyle=&quot;1&quot; w:styleId=&quot;Superscript&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot;&gt;
        ///  &lt;w:basedOn w:val=&quot;DefaultParagraphFont&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;superscript&quot;/&gt;
        ///  &lt;w:qFormat/&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:vertAlign w:val=&quot;superscript&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;.
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;TableofFigures&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;table of figures&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:tabs&gt;
        ///      &lt;w:tab w:val=&quot;right&quot; w:leader=&quot;dot&quot; w:pos=&quot;9360&quot;/&gt;
        ///    &lt;/w:tabs&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string TableOfFigures {
            get {
                return ResourceManager.GetString("TableOfFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;a:theme xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; name=&quot;Office Theme&quot;&gt;
        ///  &lt;a:themeElements&gt;
        ///    &lt;a:clrScheme name=&quot;Office&quot;&gt;
        ///      &lt;a:dk1&gt;
        ///        &lt;a:sysClr val=&quot;windowText&quot; lastClr=&quot;000000&quot;/&gt;
        ///      &lt;/a:dk1&gt;
        ///      &lt;a:lt1&gt;
        ///        &lt;a:sysClr val=&quot;window&quot; lastClr=&quot;FFFFFF&quot;/&gt;
        ///      &lt;/a:lt1&gt;
        ///      &lt;a:dk2&gt;
        ///        &lt;a:srgbClr val=&quot;1F497D&quot;/&gt;
        ///      &lt;/a:dk2&gt;
        ///      &lt;a:lt2&gt;
        ///        &lt;a:srgbClr val=&quot;EEECE1&quot;/&gt;
        ///      &lt;/a:lt2&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string theme1 {
            get {
                return ResourceManager.GetString("theme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;TOC1&quot;  xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;toc 1&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:tabs&gt;
        ///      &lt;w:tab w:val=&quot;left&quot; w:pos=&quot;720&quot;/&gt;
        ///      &lt;w:tab w:val=&quot;right&quot; w:leader=&quot;dot&quot; w:pos=&quot;9360&quot;/&gt;
        ///    &lt;/w:tabs&gt;
        ///    &lt;w:spacing w:before=&quot;60&quot; w:after=&quot;60&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///    &lt;w:contextualSp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TOC1 {
            get {
                return ResourceManager.GetString("TOC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;TOC2&quot;  xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;TOC1&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;toc 2&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;245&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:b w:val=&quot;0&quot;/&gt;
        ///    &lt;w:color w:val=&quot;auto&quot;/&gt;
        ///    &lt;w:sz w:val=&quot;24&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string TOC2 {
            get {
                return ResourceManager.GetString("TOC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;TOC3&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;TOC2&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;toc 3&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;475&quot; w:right=&quot;432&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string TOC3 {
            get {
                return ResourceManager.GetString("TOC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;TOC4&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;toc 4&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:ind w:left=&quot;720&quot; w:right=&quot;432&quot;/&gt;
        ///    &lt;w:spacing w:after=&quot;0&quot; w:line=&quot;240&quot; w:lineRule=&quot;auto&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string TOC4 {
            get {
                return ResourceManager.GetString("TOC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;w:style w:type=&quot;paragraph&quot; w:styleId=&quot;TOCHeading&quot; xmlns:w=&quot;http://schemas.openxmlformats.org/wordprocessingml/2006/main&quot; &gt;
        ///  &lt;w:basedOn w:val=&quot;Heading1&quot;/&gt;
        ///  &lt;w:locked/&gt;
        ///  &lt;w:name w:val=&quot;TOC Heading&quot;/&gt;
        ///  &lt;w:next w:val=&quot;Normal&quot;/&gt;
        ///  &lt;w:pPr&gt;
        ///    &lt;w:numPr&gt;
        ///      &lt;w:numId w:val=&quot;0&quot;/&gt;
        ///    &lt;/w:numPr&gt;
        ///    &lt;w:outlineLvl w:val=&quot;9&quot;/&gt;
        ///  &lt;/w:pPr&gt;
        ///  &lt;w:rPr&gt;
        ///    &lt;w:rFonts w:asciiTheme=&quot;majorHAnsi&quot;/&gt;
        ///  &lt;/w:rPr&gt;
        ///&lt;/w:style&gt;
        ///.
        /// </summary>
        internal static string TOCHeading {
            get {
                return ResourceManager.GetString("TOCHeading", resourceCulture);
            }
        }
    }
}
